"""GDPR-style data export (Art. 15/20 — right of access, data portability)
and account erasure (Art. 17 — right to erasure).

Export gathers every row genuinely tied to the requesting user, read fresh
at request time — no caching, no stale snapshots.

Deletion is a REAL hard `DELETE FROM users WHERE id = ...`, not a soft
scrub. This is safe here specifically because every FK referencing
`users.id` in this schema was already deliberately designed with the
correct ON DELETE behavior for exactly this case:

  - ON DELETE CASCADE on every column that is the user's OWN private
    record (contest/elimination attempts, certificates, points ledger,
    streak, achievements, practice sessions, bookmarks, notifications,
    AI conversations/mock sessions, refresh tokens, sessions, profile,
    support tickets). These are genuinely erased — nothing about them
    makes sense to keep once the account is gone.

  - ON DELETE SET NULL on every column where the row is really SHARED
    content other users depend on for context (a chat message other room
    members read, a contest they created, a file they uploaded). These
    survive with their author/owner reference cleared — erasing the
    person without erasing content other real users still need.

No Python-side cascade logic is needed or written here: `db.delete(user)`
followed by a commit is enough, because the database-level constraints
do the rest.
"""
from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.ai import AIConversation, AIMessage
from app.models.ai_practice import AIMockSession
from app.models.contest import ContestAttempt, ContestCertificate
from app.models.elimination import EliminationInvitation, EliminationParticipant
from app.models.gamification import Achievement, PointsLedger, Streak
from app.models.practice import PracticeSession, QuestionBookmark
from app.models.social import ChatMessage, Notification
from app.models.system import AuditLog
from app.models.user import Profile, User


def _iso(value: datetime | None) -> str | None:
    return value.isoformat() if value is not None else None


async def export_user_data(db: AsyncSession, user: User) -> dict[str, Any]:
    uid = user.id

    async def rows(stmt):
        return (await db.execute(stmt)).scalars().all()

    profile = (await db.execute(select(Profile).where(Profile.user_id == uid))).scalar_one_or_none()
    contest_attempts = await rows(select(ContestAttempt).where(ContestAttempt.student_id == uid))
    contest_certificates = await rows(select(ContestCertificate).where(ContestCertificate.student_id == uid))
    points = await rows(select(PointsLedger).where(PointsLedger.student_id == uid))
    streak = (await db.execute(select(Streak).where(Streak.student_id == uid))).scalar_one_or_none()
    achievements = await rows(select(Achievement).where(Achievement.student_id == uid))
    practice_sessions = await rows(select(PracticeSession).where(PracticeSession.student_id == uid))
    bookmarks = await rows(select(QuestionBookmark).where(QuestionBookmark.student_id == uid))
    chat_messages = await rows(select(ChatMessage).where(ChatMessage.sender_id == uid))
    notifications = await rows(select(Notification).where(Notification.user_id == uid))
    elimination_participations = await rows(select(EliminationParticipant).where(EliminationParticipant.user_id == uid))
    elimination_invitations_sent = await rows(select(EliminationInvitation).where(EliminationInvitation.inviter_id == uid))
    ai_conversations = await rows(select(AIConversation).where(AIConversation.user_id == uid))
    ai_mock_sessions = await rows(select(AIMockSession).where(AIMockSession.student_id == uid))
    audit_as_actor = await rows(
        select(AuditLog).where(AuditLog.actor_id == uid).order_by(AuditLog.created_at.desc()).limit(500)
    )

    ai_messages: list[AIMessage] = []
    if ai_conversations:
        conv_ids = [c.id for c in ai_conversations]
        ai_messages = await rows(select(AIMessage).where(AIMessage.conversation_id.in_(conv_ids)))

    return {
        "export_generated_at": datetime.now(UTC).isoformat(),
        "note": "This export includes every record in Survival School's database that is "
                "personally identifiable or personally generated by this account, gathered "
                "fresh at the moment of export. It excludes only anonymous/aggregate "
                "analytics events (which never store more than a user_id, no content) and "
                "records that legally must survive account deletion unattached to you "
                "(e.g. the audit trail's action log, capped to your most recent 500 entries "
                "here for size).",
        "account": {
            "id": str(user.id),
            "email": user.email,
            "full_name": user.full_name,
            "is_email_verified": user.is_email_verified,
            "totp_enabled": user.totp_enabled,
            "created_at": _iso(user.created_at),
            "last_login_at": _iso(user.last_login_at),
        },
        "profile": None if profile is None else {
            "public_handle": profile.public_handle, "bio": profile.bio, "avatar_url": profile.avatar_url,
            "timezone": profile.timezone, "locale": profile.locale,
        },
        "contest_attempts": [
            {"contest_id": str(c.contest_id), "score_percent": c.score_percent, "rank": c.rank,
             "status": c.status, "submitted_at": _iso(c.submitted_at)}
            for c in contest_attempts
        ],
        "contest_certificates": [
            {"certificate_number": c.certificate_number, "contest_title": c.contest_title,
             "rank": c.rank, "issued_at": _iso(c.issued_at)}
            for c in contest_certificates
        ],
        "points_ledger": [
            {"amount": p.amount, "reason": p.reason, "awarded_at": _iso(p.created_at)} for p in points
        ],
        "total_points": sum(p.amount for p in points),
        "streak": None if streak is None else {
            "current_streak_days": streak.current_streak_days,
            "longest_streak_days": streak.longest_streak_days,
            "last_activity_date": _iso(streak.last_activity_date),
        },
        "achievements": [{"badge_id": str(a.badge_id), "awarded_at": _iso(a.awarded_at)} for a in achievements],
        "practice_sessions": [
            {"source": p.source, "score_percent": p.score_percent, "submitted_at": _iso(p.submitted_at)}
            for p in practice_sessions
        ],
        "question_bookmarks": [{"question_id": str(b.question_id), "note": b.note} for b in bookmarks],
        "chat_messages_sent": [
            {"room_id": str(m.room_id), "body": m.body, "sent_at": _iso(m.created_at)} for m in chat_messages
        ],
        "notifications": [
            {"category": n.category, "title": n.title, "body": n.body, "read_at": _iso(n.read_at), "created_at": _iso(n.created_at)}
            for n in notifications
        ],
        "elimination_battles_participated": [
            {"battle_id": str(p.battle_id), "status": p.status, "eliminated_at_round": p.eliminated_at_round}
            for p in elimination_participations
        ],
        "elimination_invitations_sent": [
            {"battle_id": str(i.battle_id), "invitee_id": str(i.invitee_id), "status": i.status}
            for i in elimination_invitations_sent
        ],
        "ai_conversations": [{"id": str(c.id), "title": c.title, "created_at": _iso(c.created_at)} for c in ai_conversations],
        "ai_messages": [
            {"conversation_id": str(m.conversation_id), "role": m.role, "content": m.content, "sent_at": _iso(m.created_at)}
            for m in ai_messages
        ],
        "ai_mock_practice_sessions": [
            {"subject": s.subject, "question_count": s.question_count, "score_percent": s.score_percent, "created_at": _iso(s.created_at)}
            for s in ai_mock_sessions
        ],
        "audit_log_as_actor": [
            {"action": a.action, "resource_type": a.resource_type, "resource_id": a.resource_id,
             "result": a.result, "occurred_at": _iso(a.created_at)}
            for a in audit_as_actor
        ],
    }


async def delete_account(db: AsyncSession, user: User) -> None:
    """Hard-deletes the user row. See module docstring for why this is
    safe: every FK referencing users.id already has the correct ON DELETE
    CASCADE (own private records) or SET NULL (shared content) behavior at
    the database level."""
    await db.delete(user)
