"""add contests, ai mock practice, attendance, bulk import support, exam integrity fields

Revision ID: 31e4fc98f4cf
Revises: 6f1ba11d04f8
Create Date: 2026-08-14 10:07:54.650752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '31e4fc98f4cf'
down_revision: Union[str, None] = '6f1ba11d04f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_mock_sessions',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_percent', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_mock_sessions_student_id'), 'ai_mock_sessions', ['student_id'], unique=False)
    op.create_table('contests',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contest_type', sa.String(length=20), nullable=False),
    sa.Column('occurrence_key', sa.String(length=60), nullable=True),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('top_n_awarded', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('occurrence_key', name='uq_contest_occurrence_key')
    )
    op.create_index('ix_contests_status_ends_at', 'contests', ['status', 'ends_at'], unique=False)
    op.create_table('ai_generated_questions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_mock_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generated_questions_session_id'), 'ai_generated_questions', ['session_id'], unique=False)
    op.create_table('contest_attempts',
    sa.Column('contest_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('question_order', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('server_deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('score_percent', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('points_possible', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id', 'student_id', name='uq_contest_attempt_student')
    )
    op.create_index(op.f('ix_contest_attempts_contest_id'), 'contest_attempts', ['contest_id'], unique=False)
    op.create_index('ix_contest_attempts_contest_status', 'contest_attempts', ['contest_id', 'status'], unique=False)
    op.create_index(op.f('ix_contest_attempts_student_id'), 'contest_attempts', ['student_id'], unique=False)
    op.create_table('contest_certificates',
    sa.Column('certificate_number', sa.String(length=40), nullable=False),
    sa.Column('contest_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('contest_title', sa.String(length=200), nullable=False),
    sa.Column('score_percent', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id', 'student_id', name='uq_contest_certificate_student')
    )
    op.create_index(op.f('ix_contest_certificates_certificate_number'), 'contest_certificates', ['certificate_number'], unique=True)
    op.create_table('ai_generated_question_options',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['ai_generated_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generated_question_options_question_id'), 'ai_generated_question_options', ['question_id'], unique=False)
    op.create_table('ai_mock_answers',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_ids', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['ai_generated_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['ai_mock_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_mock_answers_session_id'), 'ai_mock_answers', ['session_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('timetable_entry_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('opened_by', sa.UUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('check_in_code', sa.String(length=10), nullable=False),
    sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timetable_entry_id'], ['timetable_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timetable_entry_id', 'session_date', name='uq_attendance_session_occurrence')
    )
    op.create_index(op.f('ix_attendance_sessions_timetable_entry_id'), 'attendance_sessions', ['timetable_entry_id'], unique=False)
    op.create_table('contest_answers',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_ids', sa.JSON(), nullable=False),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['contest_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_answers_attempt_id'), 'contest_answers', ['attempt_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('marked_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_attendance_record_student')
    )
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    # server_default required on both — autogenerate omits it, but exams is an
    # existing table that may already have rows; without a default this
    # NOT NULL ADD COLUMN fails on any non-empty table. Values match the
    # model's Python-side defaults (Exam.fullscreen_required=False,
    # Exam.integrity_monitoring_enabled=True). See docs/DATABASE.md for the
    # matching gotcha caught on the certificate migration.
    op.add_column('exams', sa.Column('fullscreen_required', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('exams', sa.Column('integrity_monitoring_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'integrity_monitoring_enabled')
    op.drop_column('exams', 'fullscreen_required')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_contest_answers_attempt_id'), table_name='contest_answers')
    op.drop_table('contest_answers')
    op.drop_index(op.f('ix_attendance_sessions_timetable_entry_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_ai_mock_answers_session_id'), table_name='ai_mock_answers')
    op.drop_table('ai_mock_answers')
    op.drop_index(op.f('ix_ai_generated_question_options_question_id'), table_name='ai_generated_question_options')
    op.drop_table('ai_generated_question_options')
    op.drop_index(op.f('ix_contest_certificates_certificate_number'), table_name='contest_certificates')
    op.drop_table('contest_certificates')
    op.drop_index(op.f('ix_contest_attempts_student_id'), table_name='contest_attempts')
    op.drop_index('ix_contest_attempts_contest_status', table_name='contest_attempts')
    op.drop_index(op.f('ix_contest_attempts_contest_id'), table_name='contest_attempts')
    op.drop_table('contest_attempts')
    op.drop_index(op.f('ix_ai_generated_questions_session_id'), table_name='ai_generated_questions')
    op.drop_table('ai_generated_questions')
    op.drop_index('ix_contests_status_ends_at', table_name='contests')
    op.drop_table('contests')
    op.drop_index(op.f('ix_ai_mock_sessions_student_id'), table_name='ai_mock_sessions')
    op.drop_table('ai_mock_sessions')
    # ### end Alembic commands ###
