"""add timetable discussions practice bookmarks

Revision ID: 6f1ba11d04f8
Revises: 8bc7896b64a9
Create Date: 2026-08-14 08:21:48.828788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6f1ba11d04f8'
down_revision: Union[str, None] = '8bc7896b64a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_sessions',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('question_order', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_percent', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('points_possible', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sessions_course_id'), 'practice_sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_student_id'), 'practice_sessions', ['student_id'], unique=False)
    op.create_table('timetable_entries',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('term', sa.String(length=40), nullable=False),
    sa.Column('term_start_date', sa.Date(), nullable=False),
    sa.Column('term_end_date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_entries_course_id'), 'timetable_entries', ['course_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_instructor_id'), 'timetable_entries', ['instructor_id'], unique=False)
    op.create_index('ix_timetable_term_day', 'timetable_entries', ['term', 'day_of_week'], unique=False)
    op.create_table('practice_answers',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_ids', sa.JSON(), nullable=False),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_answers_session_id'), 'practice_answers', ['session_id'], unique=False)
    op.create_table('question_bookmarks',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'question_id', name='uq_bookmark_student_question')
    )
    op.create_index(op.f('ix_question_bookmarks_question_id'), 'question_bookmarks', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_bookmarks_student_id'), 'question_bookmarks', ['student_id'], unique=False)
    op.create_table('discussion_threads',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('upvote_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_threads_course_id'), 'discussion_threads', ['course_id'], unique=False)
    op.create_index(op.f('ix_discussion_threads_lesson_id'), 'discussion_threads', ['lesson_id'], unique=False)
    op.create_table('discussion_replies',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_instructor_answer', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['discussion_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_replies_thread_id'), 'discussion_replies', ['thread_id'], unique=False)
    op.create_table('discussion_votes',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['discussion_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_discussion_vote_thread_user')
    )
    op.create_index(op.f('ix_discussion_votes_thread_id'), 'discussion_votes', ['thread_id'], unique=False)
    op.create_index(op.f('ix_discussion_votes_user_id'), 'discussion_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discussion_votes_user_id'), table_name='discussion_votes')
    op.drop_index(op.f('ix_discussion_votes_thread_id'), table_name='discussion_votes')
    op.drop_table('discussion_votes')
    op.drop_index(op.f('ix_discussion_replies_thread_id'), table_name='discussion_replies')
    op.drop_table('discussion_replies')
    op.drop_index(op.f('ix_discussion_threads_lesson_id'), table_name='discussion_threads')
    op.drop_index(op.f('ix_discussion_threads_course_id'), table_name='discussion_threads')
    op.drop_table('discussion_threads')
    op.drop_index(op.f('ix_question_bookmarks_student_id'), table_name='question_bookmarks')
    op.drop_index(op.f('ix_question_bookmarks_question_id'), table_name='question_bookmarks')
    op.drop_table('question_bookmarks')
    op.drop_index(op.f('ix_practice_answers_session_id'), table_name='practice_answers')
    op.drop_table('practice_answers')
    op.drop_index('ix_timetable_term_day', table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_instructor_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_course_id'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_index(op.f('ix_practice_sessions_student_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_course_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    # ### end Alembic commands ###
