"""add certificate skills grade score fields, course skills specialization

Revision ID: 8bc7896b64a9
Revises: aedd5b33915f
Create Date: 2026-08-14 06:44:21.668969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8bc7896b64a9'
down_revision: Union[str, None] = 'aedd5b33915f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('grade', sa.String(length=10), nullable=True))
    op.add_column('certificates', sa.Column('score_percent', sa.Integer(), nullable=True))
    # server_default required: skills_json is NOT NULL and this table can
    # already have rows (existing certificates) in a real deployment — without
    # a default, adding a NOT NULL column would fail against any non-empty table.
    op.add_column('certificates', sa.Column('skills_json', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('certificates', sa.Column('specialization', sa.String(length=200), nullable=True))
    op.add_column('certificates', sa.Column('instructor_name', sa.String(length=150), nullable=True))
    op.add_column('certificates', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('courses', sa.Column('skills', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('courses', sa.Column('specialization', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'specialization')
    op.drop_column('courses', 'skills')
    op.drop_column('certificates', 'expires_at')
    op.drop_column('certificates', 'instructor_name')
    op.drop_column('certificates', 'specialization')
    op.drop_column('certificates', 'skills_json')
    op.drop_column('certificates', 'score_percent')
    op.drop_column('certificates', 'grade')
    # ### end Alembic commands ###
