"""add composite indexes for attempt lookups

Revision ID: aedd5b33915f
Revises: 5ed05c6881ad
Create Date: 2026-08-14 03:37:00.988003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aedd5b33915f'
down_revision: Union[str, None] = '5ed05c6881ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_exam_attempts_student_exam_status', 'exam_attempts', ['student_id', 'exam_id', 'status'], unique=False)
    op.create_index('ix_quiz_attempts_student_quiz_status', 'quiz_attempts', ['student_id', 'quiz_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quiz_attempts_student_quiz_status', table_name='quiz_attempts')
    op.drop_index('ix_exam_attempts_student_exam_status', table_name='exam_attempts')
    # ### end Alembic commands ###
